### PR TITLE
style-badge styling

### PR DESCRIPTION
**Pull request by ImrozNezami**
Different badges added
Badge on icon
Small badge on avatar
Medium badge on avatar
Large badge on avatar
Screenshot (213)

### CODE REVIEW

**Review by shubhamkumar648 — COMMENTED** [review]
you could also use rem units  for height and width instead of px

**Review by sakleprajwal — COMMENTED** [review]
You can also add badge on icons, buttons as given in LMS.

**Comment by ImrozNezami** [comment]
> you could also use rem units for height and width instead of px

Okay will keep that in mind

**Comment by ImrozNezami** [comment]
> You can also add badge on icons, buttons as given in LMS.

I have done it on icons in picture it is the first one (shopping cart icon).

**Pull request merged**
